# -*- coding: utf-8 -*-
"""Salinan dari Happy Christmas Day.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SwHqmIk43WUMlnMQW-S_5dmoO-M0_9W3
"""

import matplotlib.pyplot as plt

#Data Base
tree_leaves = 10
tree_wood = 6

#Program
tree_text = ""

text = ("Happy Marry Christmas 2025")
plt.figure(figsize=(0.1, 0.3))
plt.text(
    0.5, 0.95, text,
    fontsize = 14,
    family = "DejaVu Serif",
    color = "#1b4a29",
    ha="left"
)
plt.axis("off")
plt.show()

for i in range(tree_leaves):
  space = " " * (tree_leaves - i)
  leave = "*" * (2 * i + 1)
  print(space + leave)

for j in range(tree_wood):
  space = " " * (tree_leaves - 1)
  wood = "||"
  print(space + wood)

plt.figure(figsize=(0.1, 1))
plt.text(
    0.75, 0.80,
    "May your day be filled with\npeace, warmth, and joy",
    fontsize=10,
    family="DejaVu Serif",
    ha="left",
    # va="center"
)

plt.axis("off")
plt.show()